# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Votre nom', max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prenom')),
                ('contact', models.CharField(max_length=8, verbose_name='Contact(s)')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('adresse', models.CharField(max_length=30, verbose_name='Adresse')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de cr\xe9ation')),
                ('photo', models.ImageField(default=0, upload_to='images', verbose_name='Choisir une photo')),
            ],
        ),
    ]
