# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_geek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Votre nom', max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prenom')),
                ('contact', models.CharField(max_length=8, verbose_name='Contact(s)')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('adresse', models.CharField(max_length=30, verbose_name='Adresse')),
                ('password_user', models.CharField(max_length=15, verbose_name='Mot de passe')),
                ('date_creation', models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 13, 23, 20, 29, 536051, tzinfo=utc), verbose_name='Date de cr\xe9ation')),
                ('photo', models.ImageField(default=0, upload_to='images', verbose_name='Choisir une photo')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterUniqueTogether(
            name='user_geek',
            unique_together=set([('email', 'password_user')]),
        ),
    ]
