# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 23:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0003_auto_20171113_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_geek',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 13, 23, 24, 56, 250934, tzinfo=utc), verbose_name='Date de cr\xe9ation'),
        ),
    ]
