# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0004_auto_20171113_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_geek',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date de cr\xe9ation'),
        ),
    ]
